### PR TITLE
Updated to 1.18 and 1.19

### PR DESCRIPTION
**Pull request by QuantumXenon**
This should work on 1.18.x and 1.19.x

### CODE REVIEW

**Comment by bfahrenfort** [comment]
@QuantumXenon 
You're amazing for updating this by the way!

Unfortunately, I couldn't get this working with your origins++ on Forge 1.19.2-43.1.1, still receiving an invalid player data message.

Was able to compile the PR and add XLPackets to my game without issues, but I receive the well-documented invalid player data message upon creating a world, leaving the world, and attempting to rejoin.

Update: On reading docs and messing with committed files, it seems that the injector is not firing on `handle`. Is there another name that could be tried? I know next to nothing about mod development, I'm just a tinkerer.

**Comment by QuantumXenon** [comment]
@bfahrenfort I am just getting into modding. I’ll have a look for another injector - the one originally used no longer exists, but it may have been moved or something

**Comment by QuantumXenon** [comment]
And thanks for testing it! What tests did you run? So that I can test it better then what I was doing

**Comment by bfahrenfort** [comment]
> @bfahrenfort I am just getting into modding. I’ll have a look for another injector - the one originally used no longer exists, but it may have been moved or something

I did some more reading and found what might be the problem.
The mod in this PR modifies constant value-returns for any constant value equal to 1048576 in the `handle` method of `ClientboundCustomPayloadPacket.class`, but my error log is saying that the `<init>` method is causing the error. Going to try attaching the exact same modifier mixin to `<init>` instead of `handle`, on the suspicion that `<init>` is a shadow name for the constructor.

**Comment by QuantumXenon** [comment]
@bfahrenfort Also, I have just realised that `ClientboundCustomPayloadPacket.class` should be `ServerboundCustomPayloadPacket.class`. `handle` could be replaced by `getInternalData` too.

**Comment by bfahrenfort** [comment]
> @bfahrenfort Also, I have just realised that `ClientboundCustomPayloadPacket.class` should be `ServerboundCustomPayloadPacket.class`. `handle` could be replaced by `getInternalData` too.

`ClientboundCustomPayloadPacket` is in my stacktrace as the root of the issue. More specifically, its `<init>` which is the bytecode signature for its constructor.

**Comment by bfahrenfort** [comment]
Update on just copy-pasting the current injection and replacing `handle` with `<init>`: didn't work. Consulting the spongepowered discord for a better way to modify returned constant values in a constructor, it probably failed because `<init>` is inaccessible from code in normal java programs.

**Comment by QuantumXenon** [comment]
@bfahrenfort See if that last change works

Edit: Never mind, it still has the same issue.

**Comment by bfahrenfort** [comment]
@QuantumXenon I'm getting help on how to troubleshoot from a SpongePowered dev, add `-Dmixin.debug.verbose=true` to your Minecraft launch arguments for more debug info. It seems none of the mixins are applying.

**Comment by bfahrenfort** [comment]
I GOT IT WORKING!!!

The issue was the `build.gradle` file, see https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge (huge thanks to Zidane#9492 on the Discord server for SpongePowered!).

@QuantumXenon check the pulls on your fork...

**Comment by QuantumXenon** [comment]
@bfahrenfort Great! I have just merged it now.

**Comment by QuantumXenon** [comment]
@Tfarcenim Sorry for all the additional commits, but it should be working properly now.

**Comment by bfahrenfort** [comment]
~~[QuantumXeon-XLPackets-Fork.zip](https://github.com/Tfarcenim/XLPackets/files/9469631/QuantumXeon-XLPackets-Fork.zip)~~ **(Newer version lower down)**
To those of you on google frantically searching for a solution to "invalid player data" with origins or origins++, here's a quick build of the changes just to use in the interim, since I'm unsure if this PR will be merged soon. Once there's a CurseForge release I'll remove this to not confuse anything. 

Obviously, open the JAR inside here with WinRar or another program and make sure it actually looks like the other mods inside, ideally that it looks like an earlier version of XLPackets (I'm not Curseforge, I'm a random online source and that's sketchy). If so, put the JAR in your mods folder and have fun!

**Comment by futureAppDeveloper** [comment]
> [QuantumXeon-XLPackets-Fork.zip](https://github.com/Tfarcenim/XLPackets/files/9469631/QuantumXeon-XLPackets-Fork.zip) To those of you on google frantically searching for a solution to "invalid player data" with origins or origins++, here's a quick build of the changes just to use in the interim, since I'm unsure if this PR will be merged soon. Once there's a CurseForge release I'll remove this to not confuse anything.
> 
> Obviously, open the JAR inside here with WinRar or another program and make sure it actually looks like the other mods inside, ideally that it looks like an earlier version of XLPackets (I'm not Curseforge, I'm a random online source and that's sketchy). If so, put the JAR in your mods folder and have fun!

I am still receiving the same issue as Invalid Player error when I launch Minecraft for the second time and try to join the world.

**Comment by QuantumXenon** [comment]
@futureAppDeveloper What is the error in the logs?

**Comment by bfahrenfort** [comment]
> @futureAppDeveloper What is the error in the logs?

was about to ask for this. @futureAppDeveloper If it's the same error, I'd ask that you add `-Dmixin.debug.verbose=true` to your Minecraft launch arguments and upload the full log from launch to error to a paste site like paste.gg or pastebin. Thanks for providing another test point!

Edit: Please also ensure that you extracted my .JAR from the zip I attached and put that in your mods folder. Just putting the .zip in the mods folder will not fix the error.

I just tested again, redownloading the .jar inside the .zip I uploaded, and had no issues. With `-Dmixin.debug.verbose=true` in the arguments, you're able to filter the game output for `Clientbound` to see if a line is there saying there was a successful mixin for `ClientboundCustomPayloadPacket`, and if that line exists on launch, you won't have the issue with packet size.

**Comment by futureAppDeveloper** [comment]
> 

I will have to say I am wayy in over my head. I do not know how to input arguments or anything to do with the code myself. I guess I am just someone else who can test to see if it works. Ive had issues with this mod for a long time and I am just really excited to play it on forge. I will post my error here though. 
https://paste.gg/p/anonymous/edda3bbd20164e22822c79491b549d20

**Comment by bfahrenfort** [comment]
> I will have to say I am wayy in over my head. I do not know how to input arguments or anything to do with the code myself. I guess I am just someone else who can test to see if it works. Ive had issues with this mod for a long time and I am just really excited to play it on forge. I will post my error here though. https://paste.gg/p/anonymous/edda3bbd20164e22822c79491b549d20

`[13:43:20] [main/INFO]: Found mod file apoli-forge-1.19.2-2.3.4.4.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@4f186450`

Please try replacing apoli with version 1.19.2-2.5.1. you can obtain it from here: https://github.com/apace100/apoli/releases/tag/v2.5.1

**Comment by futureAppDeveloper** [comment]
> > @futureAppDeveloper What is the error in the logs?
> 
> was about to ask for this. @futureAppDeveloper If it's the same error, I'd ask that you add `-Dmixin.debug.verbose=true` to your Minecraft launch arguments and upload the full log from launch to error to a paste site like paste.gg or pastebin. Thanks for providing another test point!
> 
> Edit: Please also ensure that you extracted my .JAR from the zip I attached and put that in your mods folder. Just putting the .zip in the mods folder will not fix the error.
> 
> I just tested again, redownloading the .jar inside the .zip I uploaded, and had no issues. With `-Dmixin.debug.verbose=true` in the arguments, you're able to filter the game output for `Clientbound` to see if a line is there saying there was a successful mixin for `ClientboundCustomPayloadPacket`, and if that line exists on launch, you won't have the issue with packet size.

Are you able to update the .zip file so I can redownload and let you all know of any errors?

**Comment by bfahrenfort** [comment]
> Are you able to update the .zip file so I can redownload and let you all know of any errors?

It's likely not an issue with XLPackets, as you receive a different error to what we resolved. Going to try and resolve it in this thread anyway.

**Comment by futureAppDeveloper** [comment]
> > Are you able to update the .zip file so I can redownload and let you all know of any errors?
> 
> It's likely not an issue with XLPackets, as you receive a different error to what we resolved. Going to try and resolve it in this thread anyway.

Here is another error I received for Invalid Player Data https://paste.gg/p/anonymous/93a0ca3510634f6c9391fd28f6ae0ecc

**Comment by bfahrenfort** [comment]
> > > Are you able to update the .zip file so I can redownload and let you all know of any errors?
> > 
> > 
> > It's likely not an issue with XLPackets, as you receive a different error to what we resolved. Going to try and resolve it in this thread anyway.
> 
> Here is another error I received for Invalid Player Data https://paste.gg/p/anonymous/93a0ca3510634f6c9391fd28f6ae0ecc

This error is confirmed to be caused by outdated versions of Apoli by myself and another tester. Please follow the link I gave a few posts ago for Apoli 2.5.1, delete 2.4.3.3 in your mods folder, and put 2.5.1 in instead.

**Comment by futureAppDeveloper** [comment]
> > > > Are you able to update the .zip file so I can redownload and let you all know of any errors?
> > > 
> > > 
> > > It's likely not an issue with XLPackets, as you receive a different error to what we resolved. Going to try and resolve it in this thread anyway.
> > 
> > 
> > Here is another error I received for Invalid Player Data https://paste.gg/p/anonymous/93a0ca3510634f6c9391fd28f6ae0ecc
> 
> This error is confirmed to be caused by outdated versions of Apoli by myself and another tester. Please follow the link I gave a few posts ago for Apoli 2.5.1, delete 2.4.3.3 in your mods folder, and put 2.5.1 in instead.

for 1.19.2 there is only two versions of Origins and I noticed I can continue playing the same world if I just update or downgrade the version before I get back on the world.

**Comment by bfahrenfort** [comment]
> for 1.19.2 there is only two versions of Origins and I noticed I can continue playing the same world if I just update or downgrade the version before I get back on the world.

You're using the right version of Origins, but Origins depends on a mod called Apoli, and Curseforge downloads the wrong version for some reason. You won't have this `java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_item_action] was missing.` if you update Apoli by doing what I specified.

My working configuration: 

XLPackets (my testbuild)
Pehkui-3.4.1+1.19.2
origins-plus-plus-1.7
origins-forge-1.19.2-1.5.0.6-all
caelus-forge-1.19.2-3.0.0.6
Apoli-1.19-2.5.1

Please check your mods folder for all of the above. If one of them is missing or a different version, you need to obtain the exact version I have.

**Comment by bfahrenfort** [comment]
@QuantumXenon Please let me know once you're finished refactoring and tinkering with the build configuration so I can roll a new build, test it, and update my uploaded interim jar, thanks!

**Comment by QuantumXenon** [comment]
@bfahrenfort I should be done now

**Comment by bfahrenfort** [comment]
> @bfahrenfort I should be done now

With this new version, I'm actually receiving `java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_item_action] was missing.` 

The world I created to test the new version that I received the above error after quitting and rejoining was also corrupted somehow by the new version. I was not prompted to select an origin on first join, and after replacing with my original working jar I was not prompted either (and couldn't get the prompt to show with an Orb of Origin). 

After replacing with my working jar, I was able to get back into worlds I previously created and origin powers worked as expected.

You removed and modified a lot of stuff in the build.gradle, please follow https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge or just look at the version in my merge to ensure that everything needed is there. check #[12365e5](https://github.com/Tfarcenim/XLPackets/pull/7/commits/12365e540f5ca6463578e6d0fe71a8b574c8a397)

**Comment by QuantumXenon** [comment]
@bfahrenfort Sorry about that, I added back the repository that I had moved to `settings.gradle`. Other than that, everything should be there - I was mostly adding brackets to make it a bit cleaner

**Comment by QuantumXenon** [comment]
If that doesn't work, I'll go all the way back to the original that is confirmed to work

Edit: Rolled back to an old version and now it seems to work.

Edit 2: I'm just going to leave it how it is now as it works and I don't want to break it.

Edit 3: Never mind, I'm rolling it back and not touching it

**Comment by futureAppDeveloper** [comment]
> > @bfahrenfort I should be done now
> 
> With this new version, I'm actually receiving `java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_item_action] was missing.`
> 
> The world I created to test the new version that I received the above error after quitting and rejoining was also corrupted somehow by the new version. I was not prompted to select an origin on first join, and after replacing with my original working jar I was not prompted either (and couldn't get the prompt to show with an Orb of Origin).
> 
> After replacing with my working jar, I was able to get back into worlds I previously created and origin powers worked as expected.
> 
> You removed and modified a lot of stuff in the build.gradle, please follow https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge or just look at the version in my merge to ensure that everything needed is there. check #[12365e5](https://github.com/Tfarcenim/XLPackets/pull/7/commits/12365e540f5ca6463578e6d0fe71a8b574c8a397)


So I guess I finally got the Mod to work on forge, but the world keeps becoming unresponsive after a while. I will break a block and nothing will drop and all AI stop moving or responding. Here is the Latest log. Can you take a look?  https://pastebin.com/vp70zYz9

**Comment by bfahrenfort** [comment]
> > > @bfahrenfort I should be done now
> 
> > 
> 
> > With this new version, I'm actually receiving `java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_item_action] was missing.`
> 
> > 
> 
> > The world I created to test the new version that I received the above error after quitting and rejoining was also corrupted somehow by the new version. I was not prompted to select an origin on first join, and after replacing with my original working jar I was not prompted either (and couldn't get the prompt to show with an Orb of Origin).
> 
> > 
> 
> > After replacing with my working jar, I was able to get back into worlds I previously created and origin powers worked as expected.
> 
> > 
> 
> > You removed and modified a lot of stuff in the build.gradle, please follow https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge or just look at the version in my merge to ensure that everything needed is there. check #[12365e5](https://github.com/Tfarcenim/XLPackets/pull/7/commits/12365e540f5ca6463578e6d0fe71a8b574c8a397)
> 
> 
> 
> 
> 
> So I guess I finally got the Mod to work on forge, but the world keeps becoming unresponsive after a while. I will break a block and nothing will drop and all AI stop moving or responding. Here is the Latest log. Can you take a look?  https://pastebin.com/vp70zYz9

That log doesn't have any useful info on that problem. This is no longer a problem with XLPackets/Apoli/Origins++, and is now just a general modded Minecraft problem. I'd suggest first allocating more ram, and if that doesn't work, please find another forum to ask for help on so we don't clutter this pull request. Thanks for letting us know you were able to get it working!

**Comment by bfahrenfort** [comment]
Built from #[478e382](https://github.com/Tfarcenim/XLPackets/pull/7/commits/478e3829bdee4892734f1beda33e3c7071387f70) and it's working. Should be good to go!
[XLPackets-1.19.2-TESTBUILD.zip](https://github.com/Tfarcenim/XLPackets/files/9481184/XLPackets-1.19.2-TESTBUILD.zip)

**Comment by Mysticpasta1** [comment]
Can someone in here please put this on Curseforge

**Comment by Mysticpasta1** [comment]
I need the 1.18.2 forge version on there please

**Pull request closed without merging**
